SCRUM-36 EncryptionUtil
utn-integrador-III/security-service-api pull request #1
Opened 2024-06-15 05:27 UTC by Remma27

https://ever-utn.atlassian.net/browse/SCRUM-36

Guia de uso

En .env agregar variable de entorno ENCRYPTION_PASSWORD con un valor seguro, por ejemplo "kpA!3s7zZ@M1dL9qBh*Y4jX6e$PnTv2F".

from encryption_utils import EncryptionUtil

# Create an instance of the EncryptionUtil class
encryption_util = EncryptionUtil()

# Encrypt a secret message
plaintext = "This is a secret message"
encrypted_text = encryption_util.encrypt(plaintext) print(f'Encrypted: {encrypted_text}')

# Decrypt the encrypted message
decrypted_text = encryption_util.decrypt(encrypted_text) print(f'Decrypted: {decrypted_text}')

2024-06-17 14:35 UTC, ebarahonautn requested changes

2024-06-17 14:35 UTC, ebarahonautn commented on utils/encryption_utils.py
@Remma27 
 - Agregar la variable ENCRYPTION_PASSWORD en el .ev.example sin el valor (porque el repo es publico y no revelar la palabra de validacion en la encriptacion)
- Agregar la variable ENCRYPTION_PASSWORD con su respectivo valor en el archivo onenote en un apartado de security


ENCRYPTION_PASSWORD=

2024-06-17 20:30 UTC, ebarahonautn approved these changes

2024-06-19 22:06 UTC, AnisanYT approved these changes
Perfecto.

2024-06-19 23:05 UTC, Remma27 commented
Hacer merge please

2024-06-19 23:23 UTC, merged