US-116
utn-integrador-III/security-service-api pull request #19
Opened 2024-07-24 18:36 UTC by JhonAllen01

Este endpoint se ejecutará cuando un usuario necesite restablecer una contraseña (opción de olvidó una contraseña en la interfaz). Este punto de conexión se aplicará:

Crear un nuevo código de caducidad

Crear nuevo tiempo de caducidad (5 minutos)

Cambiar el estado = 'Bloqueado'

Crear una contraseña temporal: el código temporal será la primera parte del correo electrónico del usuario y se concatenará con el código de verificación.

Punto de conexión POST: /user/password

Documentacion del endpoint en swagger.yml

2024-07-26 17:00 UTC, ebarahonautn requested changes

2024-07-26 17:00 UTC, ebarahonautn commented on swagger.yml
@JhonAllen01 
- this endpoint is POST **/user/password*, then, remove **/user/reset-password**
- Delete the attribute data in the response, because, the user will receive the new password by email

Correct response 

```
{
  "message": "Password reset initiated and user blocked",
  "message_code": "PASSWORD_RESET_INITIATED"
}
```

2024-07-26 18:22 UTC, JhonAllen01 commented
![evidencia_1](https://github.com/user-attachments/assets/6f09a7b8-7613-4c8e-860b-1d8aa55c17c8)
![evidencia_2](https://github.com/user-attachments/assets/0ac0950f-6f58-4ee0-ba60-71bea3cea9f6)
![evidencia_3](https://github.com/user-attachments/assets/0d0846c9-d0fd-4617-a6b0-388ecfc49903)

2024-07-27 00:38 UTC, ebarahonautn approved these changes

2024-07-27 00:43 UTC, merged