UserEnrollment Fixed and Save Token
utn-integrador-III/security-service-api pull request #20
Opened 2024-07-25 01:05 UTC by Remma27

2024-07-25 01:44 UTC, Remma27 commented
![UserEnrollment Fixed and Save Token](https://github.com/user-attachments/assets/4f1f16ba-cd7b-4b19-8654-473e6e550f5d)

2024-07-26 17:30 UTC, ebarahonautn requested changes

2024-07-26 17:30 UTC, ebarahonautn commented on utils/email_validator.py
@Remma27 please only validate the email contains **utn.ac.cr**

because the emails can be **@adm.utn.ac.cr** or **@est.utn.ac.cr** or **@utn.ac.cr**

2024-07-26 17:30 UTC, ebarahonautn commented on db/mongo_client.py
@Remma27 delete the method update_token() you can user the method called: update_by_condition() that it already exists

2024-07-26 17:30 UTC, ebarahonautn commented on models/user/db_queries.py
@Remma27 no use `self.collection.update_one()` instead of please use `self.update_by_condition()`"
 
and when storing the token, please set **is_session_active = true**

2024-07-27 00:35 UTC, ebarahonautn approved these changes

2024-07-27 00:35 UTC, merged