Us 111
utn-integrador-III/security-service-api pull request #21
Opened 2024-07-25 02:59 UTC by edduardaq

2024-07-26 18:15 UTC, ebarahonautn requested changes

2024-07-26 18:15 UTC, ebarahonautn commented on db/mongo_client.py
@DevWilliamCN delete the  **update_verification_code()** method, you can use the method **update_by_condition()**

2024-07-26 18:15 UTC, ebarahonautn commented on controllers/auth/VerifyCodeController.py
@DevWilliamCN this is a **PUT** and not a POST

- This controller needs to be created in **controllers/user/UserVerificationController.py**
-  the correct route is **/user/verification**
- Delete this code:    ` STATIC_VERIFICATION_CODE = 123456`  # Código de verificación estático para pruebas
- the method no apply all changes in the DB, please review carefully the user story: [https://ever-utn.atlassian.net/browse/US-111](https://ever-utn.atlassian.net/browse/US-111)

2024-07-26 18:15 UTC, ebarahonautn commented on controllers/user/UserEnrollment_controller.py
@DevWilliamCN you don't need to apply changes in this controller

2024-07-26 18:15 UTC, ebarahonautn commented on models/auth/auth.py
@DevWilliamCN the models/auth folder is not longer used and exists. Please revert this change.

2024-07-26 18:15 UTC, ebarahonautn commented on models/user/user.py
@DevWilliamCN no use `__dbmanager__.update_data()`, better use `__dbmanager__.update_by_condition()`

change the method name of **save_to_db()** for this: **user_activation()**

2024-07-26 18:23 UTC, ebarahonautn requested changes
@DevWilliamCN fix the conflicts you have in the PR

2024-07-27 17:27 UTC, DevWilliamCN commented on db/mongo_client.py
Listo profe, fue corregido

2024-07-27 17:27 UTC, DevWilliamCN commented on controllers/auth/VerifyCodeController.py
Ready teacher, it was corrected

2024-07-27 17:27 UTC, DevWilliamCN commented on controllers/user/UserEnrollment_controller.py
Ready teacher, it was corrected

2024-07-27 17:27 UTC, DevWilliamCN commented on models/auth/auth.py
Ready teacher, it was corrected

2024-07-27 17:27 UTC, DevWilliamCN commented on models/user/user.py
Ready teacher, it was corrected

2024-07-31 01:11 UTC, ebarahonautn requested changes

2024-07-31 01:11 UTC, ebarahonautn commented on service.py
@DevWilliamCN you don't need to add the **UserVerificationController**

2024-07-31 01:11 UTC, ebarahonautn commented on controllers/auth/VerifyCodeController.py
@DevWilliamCN this controller is not required. Please delete this file: **controllers/auth/VerifyCodeController.py**

2024-07-31 04:33 UTC, DevWilliamCN commented on service.py
Ready

2024-08-01 02:37 UTC, ebarahonautn requested changes

2024-08-01 02:37 UTC, ebarahonautn commented on service.py
@DevWilliamCN I was wrong, please add the following code in the service

**from controllers.user.user import UserVerificationController
api.add_resource(UserVerificationController, UserVerificationController.route)**

Sorry for my mistake.

2024-08-01 03:29 UTC, DevWilliamCN commented on service.py
It's ready

Modification completed

2024-08-10 00:20 UTC, merged