SCRUM-44
utn-integrador-III/security-service-api pull request #4
Opened 2024-06-19 23:37 UTC by chrisOMG33

Se creó un endpoint para inscripción de usuarios, dicho endpoint genera un código que tendrá una fecha/hora expiración.

2024-06-20 01:38 UTC, ebarahonautn requested changes

2024-06-20 01:38 UTC, ebarahonautn commented on controllers/health/user_controller.py
@chrisOMG33 
Cambiar el codigo 400 por la respectiva variable

2024-06-20 01:46 UTC, AnisanYT reviewed
Borrar comentarios del código, por favor. 
@chrisOMG33

2024-06-21 21:22 UTC, ebarahonautn requested changes

2024-06-21 21:22 UTC, ebarahonautn commented on app.py
@chrisOMG33 
Revertir los cambios del app.py

Debe seguir la misma estructura del proyecto donde el route se hace en el service.py

2024-06-21 21:22 UTC, ebarahonautn commented on service.py
@chrisOMG33 
Debe agregar el route del nuevo controller que debe crear.

2024-06-21 21:22 UTC, ebarahonautn commented on models/health/user.py
@chrisOMG33 
el user.py debe estar en otra carpeta dentro de models

revisar este branch https://github.com/utn-integrador-III/security-service-api/tree/SCRUM-28

En el modelo no debe utilizar directamente el MOngoClient, debe haber un archivo db_queries.py
Revisar: https://github.com/utn-integrador-III/security-service-api/tree/SCRUM-28

Ajuste la estructura del codigo en el modelo.

2024-06-26 20:19 UTC, closed without merging