Scrum 44 & parte del SCRUM 55
utn-integrador-III/security-service-api pull request #5
Opened 2024-06-26 21:19 UTC by chrisOMG33

Endpoint de inscripción de usuarios, también se implemento que el password se almacene encriptado cuando se inserta un nuevo usuario.

2024-06-28 17:30 UTC, ebarahonautn requested changes

2024-06-28 17:30 UTC, ebarahonautn commented on models/user/user.py
@chrisOMG33 @Remma27 
crear la connectividad de mongo usando el db_queries.py y mongo_client.py

Esta encriptando el password tanto en. el model como en el controller. Solamente debe ser en un solo lugar.

2024-06-28 17:30 UTC, ebarahonautn commented on controllers/user/user_controller.py
@chrisOMG33 @Remma27 
Esta encriptando el password tanto en. el model como en el controller. Solamente debe ser en un solo lugar.

2024-06-28 17:30 UTC, ebarahonautn commented on app.py
@chrisOMG33 @Remma27 
aqui no se realiza la configuracion del routing es dentro del archivo service.py

2024-06-28 23:50 UTC, ebarahonautn requested changes

2024-06-28 23:50 UTC, ebarahonautn commented on controllers/user/user_controller.py
@Remma27 
poner todo el código del controler dentro de un try catch. Al llamar el `UserModel.create_user(user_data)` no se esta capturando una excepcion en el modelo.

2024-06-28 23:50 UTC, ebarahonautn commented on models/user/user.py
@Remma27 
Elimar el acceso a la BD dentro del modelo, debe usarse el db_queries.py y el mongo_client.py

Eliminar:
```
client = MongoClient(config('MONGO_URL'))
        db = client.get_database(config('MONGO_DB'))
        users_collection = db.get_collection(config('USER_COLLECTION'))

```

2024-06-29 01:01 UTC, angelicasiles approved these changes

2024-06-29 01:03 UTC, merged