SCRUM-69
utn-integrador-III/security-service-api pull request #9
Opened 2024-07-07 06:32 UTC by chrisOMG33

The existing endpoint with the path /register was changed to the correct /auth/enrollment & the endpoint is documented to enroll a new user. In swagger.yml add the endpoint inside the Auth section.

2024-07-11 00:59 UTC, XxKeyDarkxX commented on controllers/health/controller.py
El controllers/health/controller.py no se debía cambiar por favor dejarlo como estaba.

2024-07-11 00:59 UTC, XxKeyDarkxX commented on db/mongo_client.py
Esto de db/mongo_client.py tampoco debía cambiar favor dejarlo como estaba.

2024-07-11 00:59 UTC, XxKeyDarkxX commented on models/health/model.py
Aquí en models/health/model.py también dejarlo como estaba

2024-07-11 01:05 UTC, XxKeyDarkxX requested changes
Revisar los comentarios para realizar los cambios

2024-07-12 21:37 UTC, XxKeyDarkxX approved these changes

2024-07-13 02:59 UTC, ebarahonautn requested changes

2024-07-13 02:59 UTC, ebarahonautn commented on swagger.yml
Swagger.yml does not have the parameters to be sent in the request:
![image](https://github.com/user-attachments/assets/8c36d65a-1545-4985-a6be-f2613bc457bc)

for example, you need to add the parameters into the swagger such as:

{
   "email": "asolano@est.utn.ac.cr",
   "password": "p@ssw0d123"
}

2024-07-13 03:44 UTC, AnisanYT approved these changes
Excelente.

2024-07-13 03:54 UTC, XxKeyDarkxX approved these changes

2024-07-13 06:25 UTC, ebarahonautn approved these changes

2024-07-13 06:25 UTC, merged